export default {
    appName : 'فلوسي',
     tap:{
        Plan:'الخطة',
        Home:'الرئيسية',
        Report:'الميزانية',
        Setting:'الاعدادات'
            },
        TitleIntroScreen: ['تتبع نفقاتك ودخلك','حدد ميزانيتك الشهرية','حدد أهدافك المالية'],
        ContentIntroScreen:['سنساعدك على معرفة أين يذهب مالك وكيف تحافظ على دخلك','تحديد ميزانية شهرية سيساعدك كثيرا على التوفير لادخار المزيد من المال',
        'هل تخطط لشراء شىء ؟ \n تستطيع تحديد هدف شراء منزل مثلا بموعد محدد وتتبع التقدم'],
        Register:'تسجيل حساب',
        Login:'دخول',
        Next:'التالى',
        ChooseIcon:'اختر أيقونة معبرة',
        forgetPassword : 'نسيت كلمة المرور',
        fbLogin:'الدخول بواسطة فيسبوك',
        fbRegister : 'تسجيل حساب بواسطة فيسبوك',
        googleLogin : 'الدخول بواسطة جوجل',
        googleRegister : 'تسجيل حساب بواسطة جوجل',
        email : 'البريد الإلكتروني',
        password : 'كلمة المرور',
        name : 'الإسم',

        monthlyReport : 'تقرير شهري',
        Income : 'الدخل',
        Expenses : 'المصروفات',
        inWallet : 'في محفظتك',
        currencyLE : 'جنيه',

 headingIcomeScreen : 'عنوان رئيسي',
        description : 'أضف دخلك لهذا الشهر لمراقبته',
        save:'حفظ',
        noPlans : 'لا يوجد خطط',
        newPlan : 'خطة جديدة',
        newBudget : 'ميزانية جديدة',
        chooseIcon : 'أختار أيقونة',
        success : 'نجاح',
        budgets : 'ميزانيات',
        chooseCat : 'أختار النوع',
        budget : 'ميزانية',
        startDate : 'تاريخ البدأ',
        endDate : 'تاريخ الأنتهاء',
        noBudgets : 'لا يوجد ميزانيات',
        plans : 'خطط',
        incomeAdded : 'تم إضافة الدخل بنجاح',
        validNumber : 'برجاء إدخال رقم صحيح',
        alertChooseType : 'برجاء إختيار النوع',

        accountset : ' الأعدادات',
        changeLang : 'تغيير اللغة',
        changeCur : 'تغيير العملة',
        exportImport : 'استخراج البيانات وإدخالها',
   
}