export default {
    appName : 'FlOOSY',

        TitleIntroScreen: [
            'Track your expenses and incomes',
            'Set your budgets',
            'Add your financial goals'],
        ContentIntroScreen:[
            'This app helps you to know where your money goes to save it.',
            'Save more by setting budgets.',
            'Need to buy something. Add a goal for it.'],
        Register:'Register',
        Login:'Login',
        Next:'Next',
        ChooseIcon:'Choose Descriptive Icon',
        forgetPassword : 'Forget Password',
        fbLogin:'Login with facebook',
        fbRegister : 'Register with facebook',
        googleLogin : 'Login with google',
        googleRegister : 'Register with google',
        email : 'Email Address',
        password : 'Password',
        name : 'Name',


        monthlyReport : 'Monthly Report',
        Income : 'Income',
        Expenses : 'Expenses',
        inWallet : 'In your wallet',
        currencyLE : 'LE',

        headingIcomeScreen : 'Heading Title',
        description : 'add your income from this month to monitor',
        save:'save',
        noPlans : 'No Plans',
        newPlan : 'New Plan',
        newBudget : 'New Budget',
        chooseIcon : 'Choose Icon',
        success : 'success',
        budgets : 'Budgets',
        chooseCat : 'Choose Category',
        budget : 'Budget',
        startDate : 'Start Date',
        endDate : 'End Date',
        noBudgets : 'No Budgets',
        plans : 'Plans',
        incomeAdded : 'Income Added successfully',
        validNumber : 'Please enter valid number',
        alertChooseType : 'Please Choose Category Type',

        accountset : 'Account settings',
        changeLang : 'Change Language',
        changeCur : 'Change Currency',
        exportImport : 'Export and Import Data',
    }