export const Colors = {
    WhiteColor: '#ffffff',
    MoveColor: '#9459A7',
    DarkGrayColor: '#5E5E5E',
    GrayColor: '#EFF0FE',
    MediumGrayColor: '#EAEEF1',
    BigMediumColor: '#D9D9D9',
    WhiteBlueColor: '#65AFEE',
    GreenColor: '#31A54F',
    BlueColor: '#4985E1',
    DarkBlueColor: '#5125F4',
    DarkWhiteColor: '#F8F8F8',
    SkyColor: '#CFDFF9',
    ExcellentBackgroundColor: '#D4CDF9',
    ExcellentTextColor: '#5A3DEE',
    VeryGoodBackgroundColor: '#EDE1EF',
    VeryGoodTextColor: '#9D82AD',
    GoodBackgroundColor: '#F0DDDF',
    GoodTextColor: '#E47B9A',
    FairBackgroundColor: '#F9D7CE',
    FairTextColor: '#F1936E',
    PoorBackgroundColor: '#F7F3D0',
    PoorTextColor: '#F3D865',
    IconCloseColor: 'red',
    background: '#F8F8F8',
    BlackColor: '#000000',
    borderColor: "#999999",
    ofWhiteColr: '#F8F8F8'


}